max-gamma = 150

profile {
    time = 7:30
    temperature = 6000
}

profile {
    time = 21:06
    temperature = 5800
}

profile {
    time = 21:12
    temperature = 5600
}

profile {
    time = 21:18
    temperature = 5400
}

profile {
    time = 21:24
    temperature = 5200
}

profile {
    time = 21:30
    temperature = 5000
}

profile {
    time = 21:36
    temperature = 4800
}

profile {
    time = 21:42
    temperature = 4600
}

profile {
    time = 21:48
    temperature = 4400
}

profile {
    time = 21:54
    temperature = 4200
}

profile {
    time = 22:00
    temperature = 4000
}

